# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc5abf2638758cae83b429b39519d8a25f17242c3ff41af0fdf3a657b5963a574cbf67d52093e469091ae75c814d2206b5f067b537cb4bf848c0343cd3ba7962

test:
  secret_key_base: a30b2cb3c65535dd937db3803b670abf4b06b4b61fe9c3c0c81da43ff51c4efcaac5fc5b8bbb7c121534a7c08ece1cf466c0a941c203dd5c14d0341566d94a63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
